name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm install --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight

      - name: Prepare for test
        run: ./cc-test-reporter before-build  --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight

      - name: Unit test with Rspec test suite
        # Coverage will be generated while running the specs using SimpleCov
        run:  npm run coverage --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight
      - name: Report coverage
        run: 
              ./cc-test-reporter after-build  --exit-code 0 -d --debug --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}


          # --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight

# name: build

# on: [push, pull_request]

# jobs:
#   test:
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest]
#         node: [12, 10]
#     name: Test ${{ matrix.os }}/${{ matrix.node }}
#     runs-on: ${{ matrix.os }}
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@master
#         with:
#           node-version: ${{ matrix.node }}    
#       - run: cd movie-knight
#       - run: npm install
#       - run: npm run build --if-present
#       - run: npm test
#         env:
#           CI: true
#   coverage:
#     name: Test and publish test coverage
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@master
#         with:
#           node-version: "12"
#       - run: cd movie-knight
#       - run: npm install
#       - uses: paambaati/codeclimate-action@v2.4.0
#         env:
#           CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#         with:
#           coverageCommand: npx jest --coverage
#           debug: true
