name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - name: Install dependencies
        run: cd movie-knight && npm install

      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CI: true
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight
          coverageLocations: "movie-knight"

      
        


# name: build

# on: [push, pull_request]

# jobs:
#   coverage:
#     name: Test and publish test coverage
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@master
#         with:
#           node-version: "12"
#       - run: npm install --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight
#       - uses: paambaati/codeclimate-action@v2.4.0
#         env:
#           CI: true
#           CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#         with:
#           coverageCommand: npm run coverage --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight








