name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master 
      - uses: actions/setup-node@master 
        with:
          node-version: "12"
      - run:  npm install --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight
      - uses: paambaati/codeclimate-action@v2.4.0
         # run tests and jacoco coverage report
      - run:
          name: Gradle build
          command: ./gradlew clean build jacocoTestReport

      # set up xml path for code climate
      - run:
          name: Set jacoco.xml path for code climate
          command: JACOCO_SOURCE_PATH=src/main/kotlin ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco

      # upload coverage on code climate
      - run:
          name: Upload code climate report
          command: ./cc-test-reporter upload-coverage 
      with: 
          node-version: "12"
        env:
          CI: true
          CC_TEST_REPORTER_ID: 9c08b8b48a20827e20adf3fedc6fa80904e8306f418ab3714f885af57e736fff
        with:
          coverageCommand: npm run coverage --prefix /home/runner/work/movie-slater-fe/movie-slater-fe/movie-knight


# name: build

# on: [push, pull_request]

# jobs:
#   test:
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest]
#         node: [12, 10]
#     name: Test ${{ matrix.os }}/${{ matrix.node }}
#     runs-on: ${{ matrix.os }}
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@master
#         with:
#           node-version: ${{ matrix.node }}    
#       - run: cd movie-knight
#       - run: npm install
#       - run: npm run build --if-present
#       - run: npm test
#         env:
#           CI: true
#   coverage:
#     name: Test and publish test coverage
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@master
#         with:
#           node-version: "12"
#       - run: cd movie-knight
#       - run: npm install
#       - uses: paambaati/codeclimate-action@v2.4.0
#         env:
#           CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#         with:
#           coverageCommand: npx jest --coverage
#           debug: true
